### ISSUE TITLE
Question: The influence of a GPU card on a model's accuracy 

### ISSUE THREAD

**Issue by MyVanitar** [humphd/have-fun-with-machine-learning#10]
Hello,

I decided to buy a GTX 1060 or GTX 1070 card to try with Deep Learning, but I am curious if the RAM size of The GPU or its bandwidth/speed will affect the accuracy of the final model or not, by comparing these two specific GPU cards.

in the other word, I want to know selecting the GTX 1060 will just cause longer training time over GTX 1070, or it will affect the accuracy of the model either.

**Comment by povils** [comment]
Well improving hardware you could reduce learning rate which determines accuracy.

**Comment by ChlorideCull** [comment]
It shouldn't affect the accuracy directly, only the training time.

**Comment by birkhofflee** [comment]
No, different graphic cards (or graphic processing units) give same results, they only affect the training time as @ChlorideCull said.
