### ISSUE TITLE
the path is not shared from os x and is not known to docker.

### ISSUE THREAD

**Issue by UHemarajU** [humphd/have-fun-with-machine-learning#13]
Hi humphd,

Present i am trying to install Caffe and DIGITS using Dockers by following your steps. 
I downloaded the Docker.

When i run this query on terminal
 --> docker run --name digits -d -p 8080:5000 -v /path/to/this/repository:/data/repo kaixhin/digits

after all downloads i am getting error at last is -->
docker: Error response from daemon: Mounts denied: 
The path path/to/this/repository is not shared from os x and is not known to docker.

Can you please tell me how to fix this.

Thank you.

**Comment by birkhofflee** [comment]
Hey there. You need to change `/path/to/this/repository` to the absolute path where you cloned this  repository.

For example, consider the following:

```
$ git clone https://github.com/humphd/have-fun-with-machine-learning
Cloning into 'have-fun-with-machine-learning'...
remote: Counting objects: 428, done.
remote: Total 428 (delta 0), reused 0 (delta 0), pack-reused 428
Receiving objects: 100% (428/428), 7.67 MiB | 1.28 MiB/s, done.
Resolving deltas: 100% (199/199), done.

$ pwd
/Users/birkhoff/dev
```

Then the repo's absolute path will be `/Users/birkhoff/dev/have-fun-with-machine-learning`. Then replace the `/path/to/this/repository` in the Docker command to `/Users/birkhoff/dev/have-fun-with-machine-learning`, and you'll be good.

**Comment by UHemarajU** [comment]
Hi humphd,

Thank you for the reply. It worked successfully. But in the Use Image Folder, when i given /tmp/images

It showing error ---> Training Images . Folder does not exist.

Here which path i have to mentioned for the Trained Images. 

Thank you.

**Comment by birkhofflee** [comment]
Hey,

First I'm not @humphd , I'm another collaborator of this project; Second, For the question you mentioned, could you please give some screenshots of the situation? Thanks.

**Comment by UHemarajU** [comment]
Hey,

I given data/repo it taken. Is it correct right ?

**Comment by UHemarajU** [comment]
Hey Sorry BrikhoffLee,

Here is the Screenshot. 
![screen shot 2017-07-24 at 12 25 42 pm](https://user-images.githubusercontent.com/15978550/28511535-473d5eee-706b-11e7-8e38-1d90f8594124.png)

Thank you.

**Comment by birkhofflee** [comment]
Try `/data/repo/data/dolphins-and-seahorses`. That was clearly written in the tutorial:

> Everything in the repository is now in the container directory `/data/repo`

**Comment by UHemarajU** [comment]
I am not getting dolphin and seahorse names, i am getting data and images names for the images.
Is there need of any server myside ?

Please see the screenshot.
![screen shot 2017-07-24 at 12 53 26 pm](https://user-images.githubusercontent.com/15978550/28512388-5cad4466-706f-11e7-8da4-636b62d7bbc3.png)

**Comment by birkhofflee** [comment]
I'm not quite sure... I guess you gave wrong path. Did you give **exactly** `/data/repo/data/dolphins-and-seahorses`?

If so, please give the result of running `docker exec -it digits ls -lah /data/repo/data/dolphins-and-seahorses` on your machine.

**Comment by UHemarajU** [comment]
After reading clearly , Ya i given the /data/repo/data/dolphins-and-seahorses it successfully created dataset as it is. 

for the command  --> docker exec -it digits ls -lah /data/repo/data/dolphins-and-seahorses

I got output like this ...
**total 12K
drwxr-xr-x  5 root root  170 Jul 24 05:40 .
drwxr-xr-x  5 root root  170 Jul 24 05:15 ..
-rw-r--r--  1 root root 8.1K Jul 24 07:22 .DS_Store
drwxr-xr-x 67 root root 2.3K Jul 24 05:11 dolphin
drwxr-xr-x 59 root root 2.0K Jul 24 05:11 seahorse**

But  While generating model i am getting Error code -9. 

Here is the screenshot.

![screen shot 2017-07-24 at 3 45 39 pm](https://user-images.githubusercontent.com/15978550/28518881-2db7853c-7087-11e7-81fa-135447bbd6bc.png)

**Comment by UHemarajU** [comment]
Hi,

Can you please help me to complete this.

Thank you.

**Comment by humphd** [comment]
@UHemarajU I'm not sure what that error `-9` is exactly, but perhaps you're hitting https://github.com/NVIDIA/DIGITS/issues/1402 or maybe running out of memory?
