### ISSUE TITLE
the issue of installation

### ISSUE THREAD

**Issue by HwaiHo-0552** [humphd/have-fun-with-machine-learning#15]
Hello，David Humphrey.
 There are some question about the framework of image classification . You installed the OPNECL caffe.  And you finished the image classification based on the Mac pro. You used the Inel graphics.  But,the DIGITS cloud be installed if you would use a nvida GPU.  
My laptop based on the AMD graphics , and i plan to run this work on VM(Ubuntu 16.04), It means that i can not install and use DIGITS ? 
Thanks for reading.

**Comment by humphd** [comment]
@digitalized-hfut yeah, you are fine with only CPU vs. GPU for this walkthrough.  DIGITS will use a GPU if it can, but will fallback to use CPU otherwise.  You'll be fine.  Good luck!

**Comment by HwaiHo-0552** [comment]
Thank you.
