### ISSUE TITLE
Docker container exits immediately upon creation

### ISSUE THREAD

**Issue by macgyverfan** [humphd/have-fun-with-machine-learning#16]
Hi there,

I have cloned the repository to GitHub desktop and run the following command with the /path/to/this/repository replaced with my local directory of the repository. 

docker run --name digits -d -p 8080:5000 -v /path/to/this/repository:/data/repo kaixhin/digits

My container exits immediately upon creation as seen when typing docker ps -a. Am I doing something wrong?

Thanks

**Comment by birkhofflee** [comment]
Hi macgyverfan, please run this command when the container exits so we can know what actually happened:

`docker logs digits`

Paste the results here. Thanks!

**Comment by macgyverfan** [comment]
BirkhoffLee please see below.

Thanks


  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 5.1-dev

Did you forget to "make pycaffe"?
"/root/caffe" from CAFFE_HOME does not point to a valid installation of Caffe.
Use the envvar CAFFE_ROOT to indicate a valid installation.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/digits/digits/__main__.py", line 70, in <module>
    main()
  File "/root/digits/digits/__main__.py", line 53, in main
    import digits.config
  File "digits/config/__init__.py", line 7, in <module>
    from . import (  # noqa
  File "digits/config/caffe.py", line 228, in <module>
    executable, version, flavor = load_from_envvar('CAFFE_HOME')
  File "digits/config/caffe.py", line 37, in load_from_envvar
    import_pycaffe(python_dir)
  File "digits/config/caffe.py", line 126, in import_pycaffe
    import caffe
  File "/root/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/root/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: /usr/lib/x86_64-linux-gnu/libopencv_highgui.so.2.4: invalid ELF header

**Comment by birkhofflee** [comment]
Mine did work. I have no idea why yours didn't.

```
birkhoff at Birkhoff-MBPR in ~/dev/have-fun-with-machine-learning (master)
$ docker run --name digits -d -p 8080:5000 -v $(pwd):/data/repo kaixhin/digits
Unable to find image 'kaixhin/digits:latest' locally
latest: Pulling from kaixhin/digits
16da43b30d89: Pull complete
1840843dafed: Pull complete
91246eb75b7d: Pull complete
7faa681b41d7: Pull complete
97b84c64d426: Pull complete
0b483d8c35bc: Pull complete
01f5c1884863: Pull complete
905f6e60ec15: Pull complete
d88440c3aa80: Pull complete
30d383ac5437: Pull complete
Digest: sha256:7a4091e1a66cc4768df5e6f03cd5c5fca1c15b4e9ee7cf9c876a2885af020ce4
Status: Downloaded newer image for kaixhin/digits:latest
c3d92781ccdcfd7929113a40bb74af7cc570461da58e600b6da6c44b0a9462c7

birkhoff at Birkhoff-MBPR in ~/dev/have-fun-with-machine-learning (master)
$ docker logs -f c3d92781ccdcfd7929113a40bb74af7cc570461da58e600b6da6c44b0a9462c7
libdc1394 error: Failed to initialize libdc1394
/usr/local/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 5.1-dev

2018-01-26 07:46:24 [INFO ] Loaded 0 jobs.
```

Try running the following commands and run the DIGITS container with *sudo* again:

```
docker stop digits
docker rm digits
docker rmi kaixhin/digits
```

**Comment by macgyverfan** [comment]
Ran the above as you said and reran without sudo and in the directory of the cloned repository so I could run the docker command exactly as you have it above and it worked.

Cheers!

**Comment by birkhofflee** [comment]
Glad to hear :)
