### ISSUE TITLE
error -9 when training caffe-alexnet model

### ISSUE THREAD

**Issue by srinivasmangipudi** [humphd/have-fun-with-machine-learning#17]
The job run for about 2 mins, but when on process#60 its crashing with the following error.see image attached.

![screen shot 2018-03-21 at 5 44 41 pm](https://user-images.githubusercontent.com/490356/37709261-aff8f3ea-2d2f-11e8-9c99-6a6bfa5211e7.png)

**Comment by humphd** [comment]
I'm not entirely sure, but my guess is that this is either your system running out of memory or a problem with it picking incorrectly between cpu vs. gpu.

Could be https://github.com/NVIDIA/DIGITS/issues/1402 ?

**Comment by ln3333** [comment]
Reproduced the error on my docker box. By default docker is allocating 2G memory for the pod on my Macbook, which is insufficient in this case. Seen from DIGITS dashboard, the training is eating up ~3G memory.

For my case, increasing memory in docker preference panel works. Navigate through the docker whale icon -> preferences -> advanced -> memory, then increase accordingly.

**Comment by humphd** [comment]
@ln3333 thanks for this, I've [added a note and pushed it](https://github.com/humphd/have-fun-with-machine-learning/commit/caf3ca00970e40a2548f343046541e54658b1906).  Closing.

I'm in the process of rewriting this for TensorFlow and TensorFlow.js right now in #14, so I think further debugging of DIGITS issues isn't necessary.
