### ISSUE TITLE
BadRequestKeyError, when uploading pertained models

### ISSUE THREAD

**Issue by xueyuanl** [humphd/have-fun-with-machine-learning#22]
Hi guys,
I hit an issue when I uploading the pertained models both Alex and google, like the below photos:
<img width="624" alt="Screen Shot 2019-04-24 at 01 32 01" src="https://user-images.githubusercontent.com/15186846/56602954-37604f00-6631-11e9-8394-ed899f6ffa74.png">

<img width="753" alt="Screen Shot 2019-04-24 at 01 32 28" src="https://user-images.githubusercontent.com/15186846/56602972-40e9b700-6631-11e9-88a6-3c45dcc158b0.png">

I have no idea about that, anybody can help me ? That would be a huge Appreciate.

**Comment by humphd** [comment]
@xueyuanl I haven't run into this before, but I do see https://github.com/NVIDIA/DIGITS/issues/2070 is filed upstream with DIGITS, indicating it might not just be you.  You might want to comment on that issue and see what it produces.

**Comment by xueyuanl** [comment]
> @xueyuanl I haven't run into this before, but I do see [NVIDIA/DIGITS#2070](https://github.com/NVIDIA/DIGITS/issues/2070) is filed upstream with DIGITS, indicating it might not just be you. You might want to comment on that issue and see what it produces.

Thanks for your help humphd.

**Comment by xueyuanl** [comment]
Is it possible the version of DIGITS in your docker template is out of date? or something like that.

**Comment by birkhofflee** [comment]
I'm not the maintainer of https://hub.docker.com/r/kaixhin/digits/, but it **do** look like a outdated version of DIGITS.

**Comment by humphd** [comment]
Would someone be willing to try this version: https://ngc.nvidia.com/catalog/containers/nvidia:digits and specifically:

`docker pull nvcr.io/nvidia/digits:19.04-caffe`

If it works for what we have here, we could update the docs.

**Comment by xueyuanl** [comment]
> Would someone be willing to try this version: https://ngc.nvidia.com/catalog/containers/nvidia:digits and specifically:
> 
> `docker pull nvcr.io/nvidia/digits:19.04-caffe`
> 
> If it works for what we have here, we could update the docs.

I read your dockerfile source code, 
`# Install DIGITS`
`ENV DIGITS_ROOT /root/digits`
`RUN git clone https://github.com/NVIDIA/DIGITS.git $DIGITS_ROOT && cd $DIGITS_ROOT && \
  pip install -r requirements.txt && \
  pip install -e .`
it always clone the latest source code. So the outdated version of digits may not the root cause.

**Comment by doggyeh** [comment]
You must upload a labels.txt file. Just create an empty file and upload it.

**Comment by xueyuanl** [comment]
Thank you guys, This issue was opened so long, and I can't remember the context about it. 
So, I just close it, and hope it would help others.
