### ISSUE TITLE
docker那句

### ISSUE THREAD

**Issue by zthcool** [humphd/have-fun-with-machine-learning#23]
原句 
docker run --name digits -d -p 8080:5000 -v $(pwd)/have-fun-with-machine-learning:/data/repo /kaixhin/digits
是不是应该把kaixhin前的“/”去掉，改为
docker run --name digits -d -p 8080:5000 -v $(pwd)/have-fun-with-machine-learning:/data/repo kaixhin/digits

**Comment by zthcool** [comment]
在繁体中文版的README_zh-tw.md教程中

**Comment by birkhofflee** [comment]
Thank you for reporting.

**Comment by zthcool** [comment]
Birkhoff Lee：
    Hi,Thank you for your tutorial about Have Fun with Machine Learning.It‘s useful for beginners like me.
    I have one problem when I run it with docker.The browser show me "BadRequestKeyError 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.The browser (or proxy) sent a request that this server could not understand." when I upload model.In the upload model UI,what files I browser is local file system.I don't know how to deal with it,I can't open file system in the docker.Could you please help me with the problem or show me a way?Thank you again.
                                                                                                                                         Tianhao Zhang
                                                                                                                                         20190430


------------------ 原始邮件 ------------------
发件人: "Birkhoff Lee"<notifications@github.com>;
发送时间: 2019年4月29日(星期一) 下午5:13
收件人: "humphd/have-fun-with-machine-learning"<have-fun-with-machine-learning@noreply.github.com>;
抄送: "张天浩"<834584812@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [humphd/have-fun-with-machine-learning] docker那句 (#23)




Thank you for reporting.

**Comment by birkhofflee** [comment]
I haven’t had this issue. You might need to check nvidia/digits repo for
the relevant issues.

**Comment by zthcool** [comment]
Ok,I will try it,Thank you anyway.


------------------ 原始邮件 ------------------
发件人: "Birkhoff Lee"<notifications@github.com>;
发送时间: 2019年4月30日(星期二) 下午4:37
收件人: "humphd/have-fun-with-machine-learning"<have-fun-with-machine-learning@noreply.github.com>;
抄送: "张天浩"<834584812@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [humphd/have-fun-with-machine-learning] docker那句 (#23)



I haven’t had this issue. You might need to check nvidia/digits repo for
 the relevant issues.

**Comment by humphd** [comment]
@zthcool another user filed a similar bug not long ago, see #22, and there is an upstream issue for this https://github.com/NVIDIA/DIGITS/issues/2070.  I'm not sure what the underlying problem is.
