### ISSUE TITLE
How to train the network on a remote server

### ISSUE THREAD

**Issue by MyVanitar** [humphd/have-fun-with-machine-learning#3]
Hello,

I like your language. it is written straightforward and easy to understand. actually that's an art if somebody has this ability. nice.

as you know GPUs are expensive, therefore do you know how we can train our model on a remote server with GPU cards (such as amazon) which we can rent hourly with low prices or similar?

**Comment by humphd** [comment]
There are a few AMIs available (e.g., https://aws.amazon.com/marketplace/pp/B01LZN28VD) and a number of tutorials, for example https://www.youtube.com/watch?v=QZaAcl_F9R0.  I've not tried it on AWS myself, so I can't say much more than this.
