### ISSUE TITLE
Translation 

### ISSUE THREAD

**Issue by birkhofflee** [humphd/have-fun-with-machine-learning#5]
Hey there. Thanks for the tutorial. Can I fork this repository and make a Chinese version of this? I really love this.

**Comment by humphd** [comment]
I think that sounds great, and if you're willing to do that work, please do.  What do you think about doing a PR and adding a `README_zh-tw.md` (i.e., with locale) file or something, and we can link it from `README.md` vs doing it as a separate repo?  Maybe others would be interested in doing more translations to other languages, who knows, and this would keep them altogether.

Totally up to you, but I'd be happy to take the patch.

**Comment by birkhofflee** [comment]
That would be cool. Planning to begin translation this Friday and the weekend. I'll reply to this issue when I start to do that.

**Comment by birkhofflee** [comment]
The work has begun: https://github.com/BirkhoffLee/have-fun-with-machine-learning/blob/master/README_zh-tw.md

**Comment by humphd** [comment]
👍

**Comment by birkhofflee** [comment]
@humphd I ain't quite familiar with the terms of machine learning -- should I just translate them into Chinese by the meaning of the words? Like `Classification Dataset`, I don't know the actual term of it in Chinese.

**Comment by humphd** [comment]
I would put a "Translator's Note" section at the top of your version, and indicate that you've done your best with technical language, but used a literal translation (i.e., translate it as best you can, and then put it in English in parenthesis or something) where you weren't sure, and ask others to submit fixes if they have suggestions.  Let the Github community help you with this.

**Comment by birkhofflee** [comment]
Alright. I'll do some kinda marking for where I ain't sure.

**Comment by humphd** [comment]
I've merged this, closing.
