### ISSUE TITLE
Renaming the layers

### ISSUE THREAD

**Issue by MyVanitar** [humphd/have-fun-with-machine-learning#6]
Hello,

How did you noticed that which layers should be renamed in GoogLeNet prototxt?

I want to fine-tune the DetectNet but I don't know which layers should be renamed. The sample of object detection with Digits did not publish such part (they have not renamed anything).

Detectnet is not that much different with GoogLeNet so the fine tuning should not be that much different. I like your fine tuning because the classification model worked quite nice and accurately with even low number of images.

**Comment by humphd** [comment]
I've never worked with DetectNet, so I can't say--everything I know about it is in this tutorial: https://github.com/NVIDIA/DIGITS/tree/master/examples/object-detection.

I would recommend asking on the [DIGITS Users](https://groups.google.com/forum/#!forum/digits-users) group.
